// <auto-generated />
using Fornspar.Data.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fornspar.Data.Migrations
{
    [DbContext(typeof(FornsparDbContext))]
    [Migration("20260427162734_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fornspar.Data.Db.Remnant", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DbId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Orientation")
                        .HasColumnType("text");

                    b.Property<int?>("RemnantPlacementDbId")
                        .HasColumnType("integer");

                    b.Property<int>("RemnantTypeDbId")
                        .HasColumnType("integer");

                    b.Property<string>("Terrain")
                        .HasColumnType("text");

                    b.HasKey("DbId");

                    b.HasIndex("RemnantPlacementDbId");

                    b.HasIndex("RemnantTypeDbId");

                    b.ToTable("Remnants");
                });

            modelBuilder.Entity("Fornspar.Data.Db.RemnantPlacement", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DbId"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DbId");

                    b.ToTable("RemnantPlacement");
                });

            modelBuilder.Entity("Fornspar.Data.Db.RemnantType", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DbId"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DbId");

                    b.ToTable("RemnantType");
                });

            modelBuilder.Entity("Fornspar.Data.Db.Remnant", b =>
                {
                    b.HasOne("Fornspar.Data.Db.RemnantPlacement", "RemnantPlacement")
                        .WithMany()
                        .HasForeignKey("RemnantPlacementDbId");

                    b.HasOne("Fornspar.Data.Db.RemnantType", "RemnantType")
                        .WithMany()
                        .HasForeignKey("RemnantTypeDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemnantPlacement");

                    b.Navigation("RemnantType");
                });
#pragma warning restore 612, 618
        }
    }
}
